"""empty message

Revision ID: 9c59941ecfc6
Revises: fa30bccf2e06
Create Date: 2022-10-07 14:51:30.578817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c59941ecfc6'
down_revision = 'fa30bccf2e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
